config/routes.rb
Rails.application.routes.draw do
  devise_for :models
  get 'dashboard/index'
  resources :emergencies
  root 'dashboard#index'

  resources :emergencies do
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :emergency
end

app/models/emergency.rb
class Emergency < ApplicationRecord

  validates :alert, presence: true, length: { minimum: 4, maximum: 30 }
  validates :location, presence: true, length: { minimum: 2, maximum: 30 }
  validates :user, presence: true, length: { minimum: 2, maximum: 30 }
  validates :date, presence: true

  has_many :comments, dependent: :destroy
  validates :alert, presence: true, length: { minimum: 5 }
end

app/models/model.rb
class Model < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @emergency = Emergency.find(params[:emergency_id])
    @comment = @emergency.comments.create(comment_params)
    redirect_to emergency_path(@emergency)
  end

  def destroy
    @emergency = Emergency.find(params[:emergency_id])
    @comment = @emergency.comments.find(params[:id])
    @comment.destroy
    redirect_to edit_emergency_path(@emergency)
  end

  private
  def comment_params
    params.require(:comment) .permit(:commenter, :body)
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
  end
end

app/controllers/emergencies_controller.rb
class EmergenciesController < ApplicationController
  def index
    @emergencies = Emergency.all
  end

  def show
    @emergency = Emergency.find(params[:id])
  end

  def new
    @emergency = Emergency.new
  end

  def edit
    @emergency = Emergency.find(params[:id])
  end

  def create
    @emergency = Emergency.new(emergency_params)

    if @emergency.save
      redirect_to @emergency
    else
      render 'new'
    end
  end

  def update
    @emergency = Emergency.find(params[:id])

    if @emergency.update(emergency_params)
      redirect_to @emergency
    else
      render 'edit'
    end
  end

  def destroy
    @emergency = Emergency.find(params[:id])
    @emergency.destroy

    redirect_to emergencies_path
  end

  private

  def emergency_params
    params.require(:emergency) .permit(:alert, :location, :user, :date)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/emergencies_helper.rb
module EmergenciesHelper
end

app/views/comments/_comment.html.erb
<p>
  <strong>Commenter:</strong>
  <%= comment.commenter %>
</p>

<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>

<%= link_to 'Destroy Comment', [comment.emergency, comment], method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-danger" %>

app/views/comments/_form.html.erb
<%= form_with(model: [ @emergency, @emergency.comments.build ], local: true) do |form| %>
  <% if @emergency.errors.any? %>
    <div class="alert alert-danger" role="alert">
      <%= pluralize(@emergency.errors.count, "error") %> prohibited
      this emergency from being saved:
    </div>
    <div id="error_explanation">
      <ul class="list-group">
        <% @emergency.errors.full_messages.each do |msg| %>
          <li class="list-group-item list-group-item-action list-group-item-warning"><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= form.label :commenter %><br>
    <%= form.text_field :commenter, class: "form-control", id:"exampleFormControlInput1", placeholder:"..." %>
  </p>

  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body, class: "form-control" %>
  </p>

  <p>
    <%= form.submit  class:"btn btn-outline-dark" %>
  </p>
<% end %>

app/views/dashboard/index.html.erb
<h1>Hello, Rails!</h1>
<%= link_to 'Securirty Dashboard', controller: 'emergencies' %>

app/views/emergencies/_form.html.erb
<div class="container">
  <%= form_with model: @emergency, local: true do |form| %>
    <% if @emergency.errors.any? %>
      <div class="alert alert-danger" role="alert">
        <%= pluralize(@emergency.errors.count, "error") %> prohibited
        this emergency from being saved:
      </div>
      <div id="error_explanation">
        <ul class="list-group">
          <% @emergency.errors.full_messages.each do |msg| %>
            <li class="list-group-item list-group-item-action list-group-item-warning"><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <p>
      <%= form.label :alert %><br>
      <%= form.text_field :alert, class: "form-control", id:"exampleFormControlInput1", placeholder:"Eg. Security Alerts" %>
    </p>

    <p>
      <%= form.label :location %><br>
      <%= form.text_field :location, class: "form-control" %>
    </p>

    <p>
      <%= form.label :user %><br>
      <%= form.text_field :user, class: "form-control" %>
    </p>

    <p>
      <%= form.label :date %><br>
      <%= form.text_field :date, class: "form-control" %>
    </p>

    <p>
      <%= form.submit  class:"btn btn-outline-dark" %>
    </p>
  <% end %>
  <%= link_to 'Back', emergencies_path, class:"btn btn-outline-info" %>
</div>

app/views/emergencies/edit.html.erb
<div class="container">
  <h1>Edit Emergency</h1>
  <%= render 'form' %>
</div>

app/views/emergencies/index.html.erb
<div class="container">
  <h1>Security Dashboard</h1>

  <table class="table">
    <thead class="thead-dark">
    <tr>
      <th scope="col">#</th>
      <th scope="col">Alert</th>
      <th scope="col">Location</th>
      <th scope="col">User</th>
      <th scope="col">Date</th>
      <th></th>
      <th></th>
      <th><button type="button" class="btn btn-link"><svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-plus" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
        <path fill-rule="evenodd" d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4z"/>
      </svg> <%= link_to 'Add New', new_emergency_path %></button></th>
    </tr>
    </thead>
    <tbody>
    <% @emergencies.each do |emergency| %>
    <tr>
      <td>
        <%= emergency.id %>
      </td>
      <td>
        <%= emergency.alert %>
      </td>
      <td>
        <%= emergency.location %>
      </td>
      <td>
        <%=emergency.user %>
      </td>
      <td>
        <%= emergency.date %>
      </td>
      <td><%= link_to 'Show', emergency_path(emergency), class: "btn btn-outline-dark" %></td>
      <td><%= link_to 'Edit', edit_emergency_path(emergency), class: "btn btn-outline-warning" %></td>
      <td><%= link_to 'Destroy', emergency_path(emergency), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-danger" %></td>
    </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/emergencies/new.html.erb
<div class="container">
  <h1>New Emergency</h1>
  <%= render 'form' %>
</div>

app/views/emergencies/show.html.erb
<div class="container">
  <p>
    <strong>Alert Type:</strong>
    <%= @emergency.alert %>
  </p>

  <p>
    <strong>Location:</strong>
    <%= @emergency.location %>
  </p>

  <p>
    <strong>User:</strong>
    <%= @emergency.user %>
  </p>

  <p>
    <strong>Date:</strong>
    <%= @emergency.date %>
  </p>

  <h2>Comments:</h2>
  <%=  render @emergency.comments %>

  <h2>Add a comment:</h2>
  <%= render 'comments/form' %>

  <%= link_to 'Back', emergencies_path, class:"btn btn-outline-dark" %>
  <%= link_to 'Edit', edit_emergency_path, class:"btn btn-outline-info" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EstateApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
  </body>
  </body>
</html>